# ==============================================================================
# FR: Fichier d'Orchestration Docker Compose (Production)
# EN: Docker Compose Orchestration File (Production)
# ==============================================================================

version: '3.8'

services:
  # FR: Service principal de l'application Portfolio Next.js
  # EN: Primary Next.js Portfolio application service
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always