sonar.host.url=https://sonarcloud.io
sonar.organization=fednel_charite
sonar.projectKey=Fednel_Charite_fednelCharite-portfolio
sonar.sources=app,components,lib
sonar.exclusions=**/*.node_modules/**,**/.next/**,**/public/**,**/ansible/**
sonar.sourceEncoding=UTF-8