sonar.projectKey=Fednel_Charite_fednelCharite-portfolio
sonar.organization=fednel_charite
sonar.sources=app,components,lib
sonar.exclusions=**/*.node_modules/**,**/.next/**,**/public/**
sonar.sourceEncoding=UTF-8